
/*********************************************************************
***                                                                 ***
***  Source code generated by cl2cpp.pl                             ***
***                                                                 ***
***  Please do not edit                                             ***
***                                                                 ***
*********************************************************************/
#include "vglImage.h"

#include "vglShape.h"

#include "vglStrEl.h"

/** Arithmetic mean of src image. Result is stored in dst image.
 */
void vglClArithmeticMean(VglImage* img_input, VglImage* img_output, int win);

/** 
    Bilateral Filter of src image. Result is stored in dst image.
 */
void vglClBilateral(VglImage* img_input, VglImage* img_output);

/* Contraharmonic mean filter of src image. Result is stored in dst image
*/
void vglClContraHarmonicMean(VglImage* img_input, VglImage* img_output, int win, float q);

/** Geometric mean of src image. Result is stored in dst image.
*/
void vglClGeometricMean(VglImage* img_input, VglImage* img_output, int win);

/*--------------------------------------------------------------------------*
 * Harmonic mean of src image. Result is stored in dst image.
 */
void vglClHarmonicMean(VglImage* img_input, VglImage* img_output, int win);

/**
 * Aplica um filtro de aguçamento (sharpen) na imagem de entrada (src)
 * usando o operador Laplaciano. O resultado é armazenado na imagem
 * de saída (dst).
 */
void vglClLaplaciano(VglImage* img_input, VglImage* img_output);

