
/*********************************************************************
***                                                                 ***
***  Source code generated by glsl2cpp.pl                           ***
***                                                                 ***
***  Please do not edit                                             ***
***                                                                 ***
*********************************************************************/
#include "vglImage.h"

void shader_15_1(VglImage* src, VglImage* dst);

/** Convert grayscale image to RGB

  */
void vgl1to3Channels(VglImage* src, VglImage* dst);

/** Inverts 3d image.

    As the wrappers are implemented currently, the shader will invert only the first layer of the 3d image.

  */
void vgl3dNot(VglImage* src, VglImage* dst);

/** Absolute difference between two images.

  */
void vglAbsDiff(VglImage* src0, VglImage* src1, VglImage* dst);

/** Logical AND between two images

  */
void vglAnd(VglImage* src0, VglImage* src1, VglImage* dst);

/** Initialize image to be used in baricenter calculation. The initialization is done by storing the values (1, x, y) in each output pixel so that the summation over th whole image gives the three moments of the image.

    R =                    f(x, y) 

    G =                x * f(x, y) 

    B =                y * f(x, y) 

  */
void vglBaricenterInit(VglImage* src, VglImage* dst);

/** vglBlurSq3

    Blur image by 3x3 square structuring element.

  */
void vglBlurSq3(VglImage* src, VglImage* dst);

/** Clear image with given color.

  */
void vglClear2(VglImage* src_dst, float r, float g, float b, float a= 0.0);

/** Changes contrast of image by given factor.

  */
void vglContrast(VglImage* src, VglImage* dst, float factor);

/** Shows coordinates of pixels as colors. Red is horizontal and green is vertical. Coordinates and colors are defined by OpenGL, that is, between 0 and 1.

  */
void vglCoordToColor(VglImage* dst);

/** Direct copy from src to dst.

  */
void vglCopy(VglImage* src, VglImage* dst);

/** Crossing number is defined as the number of ocurrences of the pattern 01
in the neihborhood of a pixel.

    Neighborhood of pixel P is indexed as follows:

\f$
\begin{array}{ccc}

    P3   &  P2   &  P1      \\ 
    P4   &  P    &  P0/8    \\
    P5   &  P6   &  P7

\end{array}
\f$


    References:

    M. Couprie, Note on fifteen 2D parallel thinning algorithms, 2006

    T. M. Bernard and A. Manzanera, Improved low complexity fully parallel
        thinning algorithms, 1999

  */
void vglCrossingNumber(VglImage* src, VglImage* dst);

/** Deletes corner from skeleton.

    Receive as input the image with the skeleton to be thinned. Receives 
    also the step. must be called once with step 1 and once with step 2.

    Neighborhood pixels is indexed as follows:

\f$
\begin{array}{ccc}

    P3  &  P2  &  P1      \\
    P4  &  P8  &  P0      \\
    P5  &  P6  &  P7

\end{array}
\f$


    Pixels deleted are the ones that mach the pattern and its rotations 
    by 90deg.

\f$
\begin{array}{ccc}

    0  &  0  &  x      \\
    0  &  1  &  1      \\
    x  &  1  &  0

\end{array}
\f$

    References:

    M. Couprie, Note on fifteen 2D parallel thinning algorithms, 2006

    T. M. Bernard and A. Manzanera, Improved low complexity fully parallel
        thinning algorithms, 1999

  */
void vglDeleteSkeletonCorners(VglImage* src, VglImage* dst, int step);

/** Deletes warts from skeleton. Receive as input the image with the skeleton to be thinned. Neighborhood pixels are indexed as follows:

\f$
\begin{array}{ccc}

    P3  &  P2  &  P1      \\
    P4  &  P   &  P0/8    \\
    P5  &  P6  &  P7

\end{array}
\f$

    Pixels deleted are the ones that mach the pattern and its rotations 
    by 45deg.

\f$
\begin{array}{ccc}

    1  &  0  &  0    \\
    1  &  1  &  0    \\
    1  &  0  &  0

\end{array}
\f$

    That is the same as delete the pixels with crossing number = 1 and 
neighbor number = 3

    References:

    Ke Liu et al., Identification of fork points on the skeletons
        of handwritten chinese characters

  */
void vglDeleteSkeletonWarts(VglImage* src, VglImage* dst);

/** Deletes warts from skeleton. Receive as input the image with the skeleton to be thinned. Neighborhood pixels are indexed as follows:

    P3 P2 P1

    P4 P  P0/8

    P5 P6 P7

    Pixels deleted are the ones that mach the pattern and its rotations 
    by 45deg.

    1 0 0
    1 1 0
    1 0 0

    1 1 0
    1 1 0
    1 0 0

    1 1 0
    1 1 0
    1 1 0

    1 1 1
    1 1 0
    1 1 0

    1 1 1
    1 1 0
    1 1 1


    That is the same as delete the pixels with crossing number = 1 and 
neighbor number >=3

    References:

    Ke Liu et al., Identification of fork points on the skeletons
        of handwritten chinese characters

  */
void vglDeleteSkeletonWarts2(VglImage* src, VglImage* dst);

/** Image src0 minus src1.

  */
void vglDiff(VglImage* src0, VglImage* src1, VglImage* dst);

/** Dilation of image by 3x3 cross structuring element.

  */
void vglDilateCross3(VglImage* src, VglImage* dst);

/** Dilation of image by 3x3 square structuring element. */
void vglDilateSq3(VglImage* src, VglImage* dst);

/** Erosion of image by 3x3 cross structuring element.

  */
void vglErodeCross3(VglImage* src, VglImage* dst);

/** Erosion of image by horizontal line with 3 pixels.

  */
void vglErodeHL3(VglImage* src, VglImage* dst);

/** Erosion of image by horizontal line with 5 pixels.

  */
void vglErodeHL5(VglImage* src, VglImage* dst);

/** Erosion of image by horizontal line with 7 pixels.

  */
void vglErodeHL7(VglImage* src, VglImage* dst);

/** Erosion of image by 3x3 square structuring element.

  */
void vglErodeSq3(VglImage* src, VglImage* dst);

/** Erosion of image by 3x3 square structuring element. Uses an offset array with 9 elements. Slower than vglErodeSq3.

  */
void vglErodeSq3off(VglImage* src, VglImage* dst);

/** Erosion of image by 5x5 square structuring element.

  */
void vglErodeSq5(VglImage* src, VglImage* dst);

/** Erosion of image by 3x3 square structuring element. Uses an offset array with 25 elements. Slower than vglErodeSq5.

  */
void vglErodeSq5off(VglImage* src, VglImage* dst);

/** Erosion of image by 7x7 square structuring element.

  */
void vglErodeSq7(VglImage* src, VglImage* dst);

/** Erosion of image by square structuring element. The parameter "side" is the dimension of the square side in pixels.

  */
void vglErodeSqSide(VglImage* src, VglImage* dst, int side);

/** Erosion of image by vertical line with 3 pixels.

  */
void vglErodeVL3(VglImage* src, VglImage* dst);

/** Erosion of image by vertical line with 5 pixels.

  */
void vglErodeVL5(VglImage* src, VglImage* dst);

/** Erosion of image by vertical line with 7 pixels.

  */
void vglErodeVL7(VglImage* src, VglImage* dst);

/** Feature Points are defined as function of the crossing number
and number of neighbors of a pixel. 

The number of neighbors is indicated as Nb. Crossing number is defined as

Nc = number of occurrences of the pattern 01 in the neighborhood of P

    Neighborhood pixels are indexed as follows:

    P3 P2 P1

    P4 P  P0

    P5 P6 P7


    All the ending points are feature points. Are defined as
Se = { P | Nc(P) = 1 }


    Feature points type 1, denoted as S1, are defined as
S1 = { P | Nc(P) >= 3}

    Feature points type 2, denoted as S2, are defined as
S1 = { P | Nb(P) >= 3}

    Feature points type 3, denoted as S3, are defined as
S3 = { P | Nc(P) >= 3 or Nb(P) >= 4 }


    References:

    Ke Liu et al., Identification of fork points on the skeletons
        of handwritten chinese characters

  */
void vglFeaturePoints(VglImage* src, VglImage* dst, int type);

/** Blurs image by 3x3 square gaussian structuring element.

  */
void vglGaussianBlurSq3(VglImage* src, VglImage* dst);


void vglGray();

